### ISSUE TITLE
I dont wan't transparent background!

### ISSUE THREAD

**Issue by mneckoee** [zzz40500/AndroidSweetSheet#11]
Hi , thanks for your widget.
I have a problem, when I use your sweet sheet background is transparent. THE IMAGE BELOW:
![device-2016-01-12-111112](https://cloud.githubusercontent.com/assets/16606340/12285613/3441744e-b9d1-11e5-8418-420b5e0634d0.png)

**Comment by zzz40500** [comment]
you can use      
"  customDelegate.setSweetSheetColor(getResources().getColor(android.R.color.white)); "

**Comment by DipakMahapurkar** [comment]
Here is got an error can not resolve symbol setSweetSheetColor()

**Comment by thalissondev-xx** [comment]
@inceptiveDipak 

Change your gradle for:

`compile 'com.github.zzz40500:AndroidSweetSheet:-SNAPSHOT'`
