### ISSUE TITLE
Error:(2, 0) Plugin with id 'com.jfrog.bintray' not found.

### ISSUE THREAD

**Issue by ahjsrhj** [zzz40500/AndroidSweetSheet#2]
ide是android studio ,  加入这个库之后sync出错，请问应该如何解决？

**Comment by zzz40500** [comment]
以源码的形式导入吗? 去掉build 中的apply plugin: 'com.jfrog.bintray'  这行再试试看

**Comment by crazycodepeng** [comment]
project 目录下的buil.gradle 的dependencies里加入
` classpath "com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.3"`
对应的最新版本可以[这里查看](https://github.com/bintray/gradle-bintray-plugin)

**Comment by ahjsrhj** [comment]
年代久远的issues

**Comment by crazycodepeng** [comment]
来自两年后的回答。。。
