### ISSUE TITLE
支持更新

### ISSUE THREAD

**Issue by hksfho** [zzz40500/AndroidSweetSheet#3]
支持新增一個dismiss listener, 設置彈出速度 二級聯動

謝

**Comment by zzz40500** [comment]
等我有空吧

**Comment by wangjinyu501** [comment]
可以支持DrawerLayout吗

**Comment by zzz40500** [comment]
@wangjinyu501  什么样子的支持

**Comment by wangjinyu501** [comment]
https://github.com/mxn21/FlowingDrawer 已经有人实现了，不过也不是使用系统DrawerLayout。
