### ISSUE TITLE
How to disable scroll of custom view

### ISSUE THREAD

**Issue by msaad99** [zzz40500/AndroidSweetSheet#9]
Hey I just created a custom view using this. How can I disable the white background that the custom view has and the top bar that is used to pull it up or down?

I just want the custom view to pop up and pop down thats it. 
![screenshot 2016-01-02 20 14 55](https://cloud.githubusercontent.com/assets/4525511/12074870/08550648-b18e-11e5-8e55-220c95f0abea.jpg)

**Comment by DipakMahapurkar** [comment]
+1

**Comment by thalissondev-xx** [comment]
+1
